Update scheduled CI pipeline
Signed-off-by: michal.gubricky <michal.gubricky@dnation.cloud>

diff --git a/.github/workflows/ci-scheduled.yaml b/.github/workflows/ci-scheduled.yaml
--- a/.github/workflows/ci-scheduled.yaml
+++ b/.github/workflows/ci-scheduled.yaml
@@ -13,65 +13,68 @@
 # limitations under the License.
 #
 
-# TODO @mfeder: Enable and update below outdated pipeline
-#name: Test Chart with k8s versions
-#
-#on:
-#  schedule:
-#    # Run every 2 weeks
-#    - cron: "0 0 1,15 * *"
-#
-#jobs:
-#  test-chart:
-#    name: test-chart
-#    runs-on: ubuntu-20.04
-#    strategy:
-#      fail-fast: false
-#      matrix:
-#        include:
-#          - k8s-version: v1.19.7
-#            stack-version: v1.3
-#          - k8s-version: v1.20.2
-#            stack-version: v1.3
-#          - k8s-version: v1.20.7
-#            stack-version: v1.4
-#          - k8s-version: v1.21.2
-#            stack-version: v1.4
-#          - k8s-version: v1.22.1
-#            stack-version: v1.4
-#          - k8s-version: v1.23.13
-#            stack-version: v2.4
-#          - k8s-version: v1.25.9
-#            stack-version: v2.5
-#
-#    steps:
-#    - name: Checkout
-#      uses: actions/checkout@v2
-#
-#    - name: Fetch history
-#      run: git fetch --prune --unshallow
-#
-#    - name: Complete semVer with highest patch version
-#      id: highest-patch
-#      run: |
-#        tag=$(git tag -l --sort=-v:refname | grep -F ${{ matrix.stack-version }}. | head -1)
-#        [[ -z $tag ]] && (echo "Patch version for ${{ matrix.stack-version }} not found!" && exit 1)
-#        echo "::set-output name=version::${tag//v}"
-#
-#    - name: Download correct chart
-#      run: |
-#        echo ${{ steps.semver.outputs.version }}
-#        wget https://dnationcloud.github.io/helm-hub/dnation-kubernetes-monitoring-stack-${{ steps.highest-patch.outputs.version }}.tgz
-#        tar -xvf dnation-kubernetes-monitoring-stack-${{ steps.highest-patch.outputs.version }}.tgz
-#
-#    - name: Create kind ${{ matrix.k8s-version }} cluster
-#      uses: helm/kind-action@v1.2.0
-#      with:
-#        node_image: kindest/node:${{ matrix.k8s-version }}
-#
-#    - name: Set up chart-testing
-#      uses: helm/chart-testing-action@v2.1.0
-#
-#    - name: Run chart-testing (install)
-#      run: |
-#        ct install --config .github/ct-scheduled.yaml
+name: Test Chart with k8s versions
+
+on:
+ schedule:
+   # Run every 2 weeks
+   - cron: "0 0 1,15 * *"
+
+jobs:
+  test-chart:
+    name: test-chart
+    runs-on: ubuntu-22.04
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+         - k8s-version: v1.28.13
+           stack-version: v3.6
+         - k8s-version: v1.29.8
+           stack-version: v3.6
+         - k8s-version: v1.30.4
+           stack-version: v3.6
+         - k8s-version: v1.28.13
+           stack-version: v3.5
+         - k8s-version: v1.29.8
+           stack-version: v3.5
+         - k8s-version: v1.30.4
+           stack-version: v3.5
+         - k8s-version: v1.28.13
+           stack-version: v3.4
+         - k8s-version: v1.29.8
+           stack-version: v3.4
+         - k8s-version: v1.30.4
+           stack-version: v3.4
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+
+    - name: Fetch history
+      run: git fetch --prune --unshallow
+
+    - name: Complete semVer with highest patch version
+      id: highest-patch
+      run: |
+        tag=$(git tag -l --sort=-v:refname | grep -F ${{ matrix.stack-version }}. | head -1)
+        [[ -z $tag ]] && (echo "Patch version for ${{ matrix.stack-version }} not found!" && exit 1)
+        echo "::set-output name=version::${tag//v}"
+
+    - name: Download correct chart
+      run: |
+        echo ${{ steps.semver.outputs.version }}
+        wget https://dnationcloud.github.io/helm-hub/dnation-kubernetes-monitoring-stack-${{ steps.highest-patch.outputs.version }}.tgz
+        tar -xvf dnation-kubernetes-monitoring-stack-${{ steps.highest-patch.outputs.version }}.tgz
+
+    - name: Create kind ${{ matrix.k8s-version }} cluster
+      uses: helm/kind-action@v1.10.0
+      with:
+        node_image: kindest/node:${{ matrix.k8s-version }}
+        config: .github/kind_cluster_config.yaml
+
+    - name: Set up chart-testing
+      uses: helm/chart-testing-action@v2.6.1
+
+    - name: Run chart-testing (install)
+      run: |
+        ct install --helm-extra-set-args "--set loki.ci=true" --config .github/ct-scheduled.yaml
